In [1]:
import numpy as np

In [2]:
arr = np.array(5)

In [3]:
arr.shape

()

In [4]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [6]:
arr1.shape # 중요 1행 3열의 1차원 배열

(3,)

In [7]:
arr2 = np.array([arr1, arr1, arr1, arr1])
arr2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [8]:
arr2.shape # 중요 4행 3열의 2차원 배열

(4, 3)

In [9]:
arr3 = np.array([arr2, arr2])
arr3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [11]:
arr3.shape # 중요 3차원 배열

(2, 4, 3)

In [12]:
arr = np.array([[1],[1],[1]])

In [13]:
arr.shape # 3행 1열의 2차원 배열

(3, 1)

In [14]:
arr = np.array([[[1]]])

In [16]:
arr.shape # 3차원 배열

(1, 1, 1)

In [17]:
zeros = np.zeros([3,4])
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
zeros.shape

(3, 4)

In [19]:
ones = np.ones([3,4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
ones.shape

(3, 4)

In [22]:
onesx5 = ones * 5 # 중요
onesx5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [23]:
onesx5 = 5 * ones # 중요
onesx5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [25]:
arr = np.arange(5) # 중요
arr

array([0, 1, 2, 3, 4])

In [26]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [27]:
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [29]:
arr = np.arange(12).reshape(3,4) # 3행 4열로 재구성
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
arr[1][2]

6

In [32]:
arr[1,2]

6

In [34]:
arr[1:] # 중요

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
arr[:,1:] # 중요, 전체를 출력하되 2열부터 출력함

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [38]:
arr[1:3, 2:4] # 중요, 2행부터 3행까지 출력하되 3열부터 4열까지 출력함

array([[ 6,  7],
       [10, 11]])

In [40]:
data = np.random.randn(3,4) # randn() 는 랜덤한 숫자를 넣음
data

array([[ 0.87608802,  1.1843238 ,  0.79406497,  0.94978873],
       [ 2.10633544,  0.94940732,  0.74505229, -0.40676819],
       [ 0.92004253,  0.62558981, -0.29186088,  0.21471325]])

In [41]:
data <= 1.0

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
data[data <= 1.0] = 0.0 # 원소들이 1.0이하이면 0.0으로 변환
data

array([[0.        , 1.1843238 , 0.        , 0.        ],
       [2.10633544, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [45]:
print(type(data)) # 파이썬의 list와 다름!

<class 'numpy.ndarray'>


In [46]:
data + 3

array([[3.        , 4.1843238 , 3.        , 3.        ],
       [5.10633544, 3.        , 3.        , 3.        ],
       [3.        , 3.        , 3.        , 3.        ]])

In [47]:
data * 3

array([[0.        , 3.55297141, 0.        , 0.        ],
       [6.31900631, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [49]:
data + np.array([1,1,1,1]) # 중요, [1,1,1,1] 벡터는 data의 모든 행에 + 되도록 전파된다.

array([[1.        , 2.1843238 , 1.        , 1.        ],
       [3.10633544, 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ]])

In [52]:
arr = np.random.randint(2, size=27).reshape(3,3,3) # 중요, random.randint(2, size=27)는 [0, 2)의 정수를 27개 넣고 reshape(3,3,3)으로 3차원 변환을 했다.
arr2 = np.random.randint(2, size=9).reshape(3,3)
arr, arr2

(array([[[1, 0, 0],
         [1, 0, 0],
         [0, 1, 1]],
 
        [[1, 0, 1],
         [0, 1, 0],
         [0, 0, 1]],
 
        [[1, 1, 0],
         [0, 1, 0],
         [1, 1, 0]]]),
 array([[0, 1, 0],
        [0, 1, 0],
        [0, 1, 0]]))

In [54]:
arr + arr2 # 중요, 2차원 배열인 arr2가 arr의 3차원 배열에 broadcasted 되었다.

array([[[1, 1, 0],
        [1, 1, 0],
        [0, 2, 1]],

       [[1, 1, 1],
        [0, 2, 0],
        [0, 1, 1]],

       [[1, 2, 0],
        [0, 2, 0],
        [1, 2, 0]]])

In [55]:
arr

array([[[1, 0, 0],
        [1, 0, 0],
        [0, 1, 1]],

       [[1, 0, 1],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 1, 0],
        [0, 1, 0],
        [1, 1, 0]]])

In [56]:
np.sum(arr)

13

In [57]:
np.max(arr)

1

In [58]:
np.min(arr)

0

In [59]:
np.mean(arr)

0.48148148148148145

In [62]:
arr = np.array([1,6,3,7,9,0])
arr

array([1, 6, 3, 7, 9, 0])

In [63]:
np.argmax(arr) # 최댓값인 9의 인덱스인 4를 출력

4

In [64]:
np.argmin(arr) # 최솟값인 0의 인덱스인 5를 출력

5

In [65]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])

In [66]:
np.unique(arr) # unique()는 중복을 지움

array([1, 3, 5, 6])

In [71]:
arr = np.array([[1.,2,3], [1,2,3]])

In [73]:
arr.dtype

dtype('float64')

In [74]:
arr.astype('int8')

array([[1, 2, 3],
       [1, 2, 3]], dtype=int8)

In [75]:
arr = np.array([[1.,2,3], [1,2,3]], dtype = np.int32)
arr.dtype

dtype('int32')

In [76]:
arr.shape

(2, 3)

In [81]:
arr = np.array([[1.,2,3], [1,2,3]]) # 1. 때문에 나머지도 float형 됨
arr.shape

(2, 3)

In [79]:
arr = arr.reshape([1,6])
print(arr, arr.shape)

[[1. 2. 3. 1. 2. 3.]] (1, 6)


In [82]:
arr = arr.reshape([6])
print(arr, arr.shape)

[1. 2. 3. 1. 2. 3.] (6,)


In [83]:
arr = arr.reshape([-1]) # 중요, the axis indicated by ‘-1’ is automatically fitted to the correct size
print(arr, arr.shape)

[1. 2. 3. 1. 2. 3.] (6,)


In [84]:
arr = arr.reshape([1, -1])
print(arr, arr.shape)

[[1. 2. 3. 1. 2. 3.]] (1, 6)


In [85]:
arr = arr.reshape([3, 2])
print(arr, arr.shape)

[[1. 2.]
 [3. 1.]
 [2. 3.]] (3, 2)


In [86]:
arr = arr.reshape([-1, 1])
print(arr, arr.shape)

[[1.]
 [2.]
 [3.]
 [1.]
 [2.]
 [3.]] (6, 1)


In [87]:
arr = np.random.randn(3,4)
print(arr, arr.shape)

[[-0.65217624 -0.91864014  1.37537914 -1.35794561]
 [-0.66238107 -0.47019183 -0.50440751 -0.18560958]
 [ 1.18555535  0.09538471 -0.55562869  0.82435843]] (3, 4)


In [88]:
arr[1,1]

-0.4701918284631209

In [89]:
arr = arr.reshape(4,3)
print(arr, arr.shape)

[[-0.65217624 -0.91864014  1.37537914]
 [-1.35794561 -0.66238107 -0.47019183]
 [-0.50440751 -0.18560958  1.18555535]
 [ 0.09538471 -0.55562869  0.82435843]] (4, 3)


In [90]:
arr[1,1]

-0.6623810681176621

In [91]:
arr = arr.reshape(-1, 2, 1)
print(arr, arr.shape)

[[[-0.65217624]
  [-0.91864014]]

 [[ 1.37537914]
  [-1.35794561]]

 [[-0.66238107]
  [-0.47019183]]

 [[-0.50440751]
  [-0.18560958]]

 [[ 1.18555535]
  [ 0.09538471]]

 [[-0.55562869]
  [ 0.82435843]]] (6, 2, 1)


In [124]:
arr = arr.reshape(-1)
arr.shape

(12,)

In [125]:
arr = np.expand_dims(arr, 0) # 중요
arr.shape

(1, 12)

In [126]:
arr = arr.reshape(-1)
arr.shape

(12,)

In [127]:
arr = np.expand_dims(arr, -1)
arr.shape

(12, 1)

In [128]:
arr = np.expand_dims(np.expand_dims(arr, -1), 0)
arr.shape

(1, 12, 1, 1)